# basic options
title: Vinisha's Blog
author: Vinisha D'Souza
email: vinisha.n.dsouza@gmail.com
description: A wonderful site
github_username: vinishadsouza

# Build settings
markdown: kramdown
theme: minima